import { dbStore, StudentRecord, AdmissionRecord, DepartmentRecord, CourseRecord, FacultyRecord, GuardianRecord, DocumentRecord, RecentActivityRecord, NotificationRecord, AlumniRecord } from '../config/db';

export class DashboardModel {
  public static seedDataIfEmpty(): void {
    // Seed Departments if empty
    if (dbStore.departments.size === 0) {
      const depts: DepartmentRecord[] = [
        {
          id: 'dept-1',
          code: 'CSE',
          name: 'Computer Science & Engineering',
          headOfDepartment: 'Prof. Ramesh Kulkarni',
          hodEmail: 'ramesh.kulkarni@scholarcore.edu.in',
          hodPhone: '+91 98765 11001',
          hodDesignation: 'Professor & HOD',
          studentCount: 1240,
          facultyCount: 58,
          coursesCount: 36,
          establishedYear: 1988,
          buildingLocation: 'Turing Block A, Floor 3',
          status: 'Active',
          description: 'Leading research department in Artificial Intelligence, Distributed Computing, Software Engineering, and Cybersecurity.',
          createdAt: new Date('2020-01-15').toISOString()
        },
        {
          id: 'dept-2',
          code: 'ECE',
          name: 'Electronics & Communication',
          headOfDepartment: 'Dr. Sunita Deshmukh',
          hodEmail: 'sunita.deshmukh@scholarcore.edu.in',
          hodPhone: '+91 98765 22002',
          hodDesignation: 'Associate Professor & HOD',
          studentCount: 820,
          facultyCount: 42,
          coursesCount: 28,
          establishedYear: 1992,
          buildingLocation: 'Bhabha Electronics Wing, Block B',
          status: 'Active',
          description: 'Specializes in VLSI Design, Embedded Systems, Signal Processing, and Next-Gen Wireless Communications.',
          createdAt: new Date('2020-02-10').toISOString()
        },
        {
          id: 'dept-3',
          code: 'EEE',
          name: 'Electrical & Electronics',
          headOfDepartment: 'Dr. K. Sivan',
          hodEmail: 'k.sivan@scholarcore.edu.in',
          hodPhone: '+91 98765 33003',
          hodDesignation: 'Professor & Chair',
          studentCount: 650,
          facultyCount: 32,
          coursesCount: 22,
          establishedYear: 1990,
          buildingLocation: 'Tesla Power Labs, Block C',
          status: 'Active',
          description: 'Focuses on Renewable Energy Integration, Smart Grids, Power Electronics, and High Voltage Engineering.',
          createdAt: new Date('2020-03-05').toISOString()
        },
        {
          id: 'dept-4',
          code: 'ME',
          name: 'Mechanical Engineering',
          headOfDepartment: 'Prof. S. N. Bose Chair',
          hodEmail: 'me.hod@scholarcore.edu.in',
          hodPhone: '+91 98765 44004',
          hodDesignation: 'Senior Chair Professor',
          studentCount: 580,
          facultyCount: 30,
          coursesCount: 20,
          establishedYear: 1985,
          buildingLocation: 'Visvesvaraya Mechanical Complex, Block D',
          status: 'Active',
          description: 'Comprehensive research in Modern Robotics, Mechatronics, Thermal Systems, and Sustainable Manufacturing.',
          createdAt: new Date('2020-01-20').toISOString()
        },
        {
          id: 'dept-5',
          code: 'BT',
          name: 'Biotechnology & Life Sciences',
          headOfDepartment: 'Dr. Kiran Mazumdar',
          hodEmail: 'kiran.m@scholarcore.edu.in',
          hodPhone: '+91 98765 55005',
          hodDesignation: 'Professor & Lead Scientist',
          studentCount: 410,
          facultyCount: 24,
          coursesCount: 18,
          establishedYear: 2005,
          buildingLocation: 'Khorana Bio-Tech Lab, Block E',
          status: 'Active',
          description: 'Cutting-edge studies in Genetic Engineering, Bioinformatics, Bioprocess Systems, and Molecular Diagnostics.',
          createdAt: new Date('2021-06-12').toISOString()
        },
        {
          id: 'dept-6',
          code: 'MBA',
          name: 'Department of Management Studies',
          headOfDepartment: 'Prof. Raghuram Rajan',
          hodEmail: 'raghuram.r@scholarcore.edu.in',
          hodPhone: '+91 98765 66006',
          hodDesignation: 'Dean & Distinguished Chair',
          studentCount: 380,
          facultyCount: 22,
          coursesCount: 16,
          establishedYear: 2000,
          buildingLocation: 'Management Tower, 5th Floor',
          status: 'Active',
          description: 'Nurturing innovative business leaders with emphasis on FinTech, Strategic Analytics, and Global Supply Chains.',
          createdAt: new Date('2020-08-15').toISOString()
        }
      ];
      depts.forEach(d => dbStore.departments.set(d.id, d));
    }

    // Seed Courses if empty
    if (dbStore.courses.size === 0) {
      const courses: CourseRecord[] = [
        {
          id: 'crs-101',
          code: 'CS101',
          title: 'Data Structures & Algorithms in C++',
          department: 'Computer Science & Engineering',
          degreeProgram: 'B.Tech CSE',
          level: 'Undergraduate',
          duration: '4 Years / 8 Semesters',
          credits: 4,
          courseFee: 85000,
          labFee: 15000,
          totalFee: 100000,
          status: 'Active',
          instructorName: 'Prof. Ramesh Kulkarni',
          maxCapacity: 360,
          enrolledStudents: 320,
          prerequisites: 'Basic C Programming & Mathematics',
          description: 'Comprehensive course covering fundamental algorithmic complexity, stacks, queues, trees, graphs, dynamic programming, and memory allocation.',
          createdAt: new Date('2025-06-10').toISOString()
        },
        {
          id: 'crs-102',
          code: 'CS204',
          title: 'Machine Learning & Artificial Intelligence',
          department: 'Computer Science & Engineering',
          degreeProgram: 'B.Tech AI&DS',
          level: 'Undergraduate',
          duration: '4 Years / 8 Semesters',
          credits: 4,
          courseFee: 92000,
          labFee: 18000,
          totalFee: 110000,
          status: 'Active',
          instructorName: 'Dr. Vikramaditya Sen',
          maxCapacity: 300,
          enrolledStudents: 285,
          prerequisites: 'Linear Algebra, Probability, Python',
          description: 'Advanced curriculum covering Supervised/Unsupervised Learning, Neural Networks, Deep Learning, Computer Vision, and Natural Language Processing.',
          createdAt: new Date('2025-06-15').toISOString()
        },
        {
          id: 'crs-103',
          code: 'EC201',
          title: 'VLSI Design & Digital Signal Processing',
          department: 'Electronics & Communication',
          degreeProgram: 'B.Tech ECE',
          level: 'Undergraduate',
          duration: '4 Years / 8 Semesters',
          credits: 4,
          courseFee: 80000,
          labFee: 12000,
          totalFee: 92000,
          status: 'Active',
          instructorName: 'Dr. Sunita Deshmukh',
          maxCapacity: 250,
          enrolledStudents: 210,
          prerequisites: 'Digital Electronics & Network Theory',
          description: 'Focuses on CMOS Logic, Verilog HDL synthesis, FPGA prototyping, DFT filters, and high-speed signal processors.',
          createdAt: new Date('2025-07-01').toISOString()
        },
        {
          id: 'crs-104',
          code: 'MB302',
          title: 'Financial Systems & Corporate Valuation',
          department: 'Department of Management Studies',
          degreeProgram: 'MBA Finance',
          level: 'Postgraduate',
          duration: '2 Years / 4 Semesters',
          credits: 3,
          courseFee: 125000,
          labFee: 10000,
          totalFee: 135000,
          status: 'Active',
          instructorName: 'Prof. Anjali Sharma',
          maxCapacity: 200,
          enrolledStudents: 190,
          prerequisites: 'Managerial Economics',
          description: 'Covers Capital Budgeting, Portfolio Theory, Mergers & Acquisitions, Financial Derivatives, and Corporate Tax Planning.',
          createdAt: new Date('2025-07-10').toISOString()
        },
        {
          id: 'crs-105',
          code: 'EE210',
          title: 'Power Electronics & Smart Grid Systems',
          department: 'Electrical & Electronics',
          degreeProgram: 'B.Tech EEE',
          level: 'Undergraduate',
          duration: '4 Years / 8 Semesters',
          credits: 4,
          courseFee: 78000,
          labFee: 12000,
          totalFee: 90000,
          status: 'Active',
          instructorName: 'Dr. Venkatesh Iyer',
          maxCapacity: 200,
          enrolledStudents: 175,
          prerequisites: 'Electric Circuits & Machines',
          description: 'In-depth study of Thyristors, Inverters, DC-DC Converters, Microgrids, EV charging systems, and Renewable Integration.',
          createdAt: new Date('2025-08-01').toISOString()
        },
        {
          id: 'crs-106',
          code: 'BT401',
          title: 'Bioprocess Engineering & Bioinformatics',
          department: 'Biotechnology & Life Sciences',
          degreeProgram: 'M.Tech Biotech',
          level: 'Postgraduate',
          duration: '2 Years / 4 Semesters',
          credits: 4,
          courseFee: 95000,
          labFee: 20000,
          totalFee: 115000,
          status: 'Active',
          instructorName: 'Dr. Priyadarshini Roy',
          maxCapacity: 150,
          enrolledStudents: 130,
          prerequisites: 'Molecular Biology & Biochemistry',
          description: 'Fermentation technology, downstream processing, BLAST sequence alignment, molecular docking, and genomic data science.',
          createdAt: new Date('2025-08-15').toISOString()
        }
      ];
      courses.forEach(c => dbStore.courses.set(c.id, c));
    }

    // Seed Faculty if empty
    if (dbStore.faculty.size === 0) {
      const facultyMembers: FacultyRecord[] = [
        { id: 'fac-1', employeeId: 'FAC-CSE-001', fullName: 'Prof. Ramesh Kulkarni', email: 'ramesh.kulkarni@scholarcore.edu.in', phone: '+91 98765 11001', department: 'Computer Science & Engineering', designation: 'HOD', qualification: 'Ph.D. in Computer Science (IISc)', joiningDate: '2012-06-15', status: 'Active' },
        { id: 'fac-2', employeeId: 'FAC-CSE-002', fullName: 'Dr. Rajesh Vardhan', email: 'rajesh.vardhan@scholarcore.edu.in', phone: '+91 98765 11002', department: 'Computer Science & Engineering', designation: 'Professor', qualification: 'Ph.D. in AI & Robotics (IIT Bombay)', joiningDate: '2015-08-01', status: 'Active' },
        { id: 'fac-3', employeeId: 'FAC-CSE-003', fullName: 'Prof. Meera Nair', email: 'meera.nair@scholarcore.edu.in', phone: '+91 98765 11003', department: 'Computer Science & Engineering', designation: 'Asst. Professor', qualification: 'M.Tech in Software Engineering (NITK)', joiningDate: '2020-01-10', status: 'Active' },
        { id: 'fac-4', employeeId: 'FAC-ECE-001', fullName: 'Dr. Sunita Deshmukh', email: 'sunita.deshmukh@scholarcore.edu.in', phone: '+91 98765 22001', department: 'Electronics & Communication', designation: 'HOD', qualification: 'Ph.D. in VLSI Systems (IIT Madras)', joiningDate: '2014-03-20', status: 'Active' },
        { id: 'fac-5', employeeId: 'FAC-ECE-002', fullName: 'Prof. Arvind Swamy', email: 'arvind.swamy@scholarcore.edu.in', phone: '+91 98765 22002', department: 'Electronics & Communication', designation: 'Professor', qualification: 'Ph.D. in Signal Processing (VTU)', joiningDate: '2017-09-15', status: 'Active' },
        { id: 'fac-6', employeeId: 'FAC-ECE-003', fullName: 'Dr. Sneha Hegde', email: 'sneha.hegde@scholarcore.edu.in', phone: '+91 98765 22003', department: 'Electronics & Communication', designation: 'Asst. Professor', qualification: 'M.Tech in Embedded Systems', joiningDate: '2021-07-05', status: 'Active' },
        { id: 'fac-7', employeeId: 'FAC-EEE-001', fullName: 'Dr. Venkatesh Iyer', email: 'venkatesh.iyer@scholarcore.edu.in', phone: '+91 98765 33001', department: 'Electrical & Electronics', designation: 'HOD', qualification: 'Ph.D. in Power Systems', joiningDate: '2011-04-10', status: 'Active' },
        { id: 'fac-8', employeeId: 'FAC-ME-001', fullName: 'Dr. Vikramaditya Rao', email: 'vikram.rao@scholarcore.edu.in', phone: '+91 98765 44001', department: 'Mechanical Engineering', designation: 'HOD', qualification: 'Ph.D. in Thermal Sciences (IIT Delhi)', joiningDate: '2013-11-01', status: 'Active' },
        { id: 'fac-9', employeeId: 'FAC-MBA-001', fullName: 'Prof. Anjali Sharma', email: 'anjali.sharma@scholarcore.edu.in', phone: '+91 98765 55001', department: 'Department of Management Studies', designation: 'HOD', qualification: 'Ph.D. in Finance & Analytics (IIMB)', joiningDate: '2010-02-15', status: 'Active' },
        { id: 'fac-10', employeeId: 'FAC-BT-001', fullName: 'Dr. Priyadarshini Roy', email: 'priyadarshini.roy@scholarcore.edu.in', phone: '+91 98765 66001', department: 'Biotechnology & Life Sciences', designation: 'HOD', qualification: 'Ph.D. in Genomic Biotech', joiningDate: '2016-05-12', status: 'Active' }
      ];
      facultyMembers.forEach(f => dbStore.faculty.set(f.id, f));
    }

    // Seed Admissions if empty
    if (dbStore.admissions.size === 0) {
      const admissions: AdmissionRecord[] = [
        {
          id: 'adm-001',
          applicationNumber: 'APP-2026-8801',
          applicantName: 'Siddharth Mukherjee',
          email: 'siddharth.m@gmail.com',
          phone: '+91 98765 12340',
          fatherName: 'Debabrata Mukherjee',
          motherName: 'Sharmila Mukherjee',
          gender: 'Male',
          dateOfBirth: '2005-04-12',
          category: 'General',
          state: 'West Bengal',
          address: 'Plot 42, Park Street, Kolkata, West Bengal 700016',
          department: 'Computer Science & Engineering',
          degree: 'B.Tech',
          academicTerm: '2026-2027 Session',
          classXPercentage: 94.2,
          classXIIPercentage: 92.8,
          entranceExamScore: 'JEE Main: 98.4 Percentile',
          status: 'Pending',
          verificationChecklist: {
            classXMarksheet: true,
            classXIIMarksheet: true,
            identityProof: true,
            migrationCertificate: false
          },
          appliedDate: new Date(Date.now() - 1000 * 60 * 30).toISOString()
        },
        {
          id: 'adm-002',
          applicationNumber: 'APP-2026-8802',
          applicantName: 'Anushka Reddy',
          email: 'anushka.reddy@gmail.com',
          phone: '+91 97654 23451',
          fatherName: 'Venkat Reddy',
          motherName: 'Sunitha Reddy',
          gender: 'Female',
          dateOfBirth: '2004-09-20',
          category: 'OBC',
          state: 'Telangana',
          address: 'Banjara Hills Road No 10, Hyderabad, Telangana 500034',
          department: 'Department of Management Studies',
          degree: 'MBA',
          academicTerm: '2026-2027 Session',
          classXPercentage: 89.0,
          classXIIPercentage: 91.5,
          entranceExamScore: 'CAT: 92.0 Percentile',
          status: 'Document Verification',
          verificationChecklist: {
            classXMarksheet: true,
            classXIIMarksheet: true,
            identityProof: true,
            casteCertificate: true,
            migrationCertificate: true,
            verifiedBy: 'Central Admissions Cell',
            verifiedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString()
          },
          appliedDate: new Date(Date.now() - 1000 * 60 * 120).toISOString()
        },
        {
          id: 'adm-003',
          applicationNumber: 'APP-2026-8803',
          applicantName: 'Rohan Deshpande',
          email: 'rohan.d@outlook.com',
          phone: '+91 96543 34562',
          fatherName: 'Anand Deshpande',
          motherName: 'Suchitra Deshpande',
          gender: 'Male',
          dateOfBirth: '2005-01-15',
          category: 'General',
          state: 'Maharashtra',
          address: '45 Prabhat Road, Erandwane, Pune, Maharashtra 411004',
          department: 'Electronics & Communication',
          degree: 'B.Tech',
          academicTerm: '2026-2027 Session',
          classXPercentage: 91.0,
          classXIIPercentage: 89.5,
          entranceExamScore: 'MHT-CET: 97.2 Percentile',
          status: 'Approved',
          generatedStudentId: '2026ECE1042',
          enrolledStudentId: 'std-301',
          verificationChecklist: {
            classXMarksheet: true,
            classXIIMarksheet: true,
            identityProof: true,
            migrationCertificate: true,
            verifiedBy: 'Sunita Deshmukh (Registrar)',
            verifiedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString()
          },
          appliedDate: new Date(Date.now() - 1000 * 60 * 360).toISOString()
        },
        {
          id: 'adm-004',
          applicationNumber: 'APP-2026-8804',
          applicantName: 'Tanvi Bhatnagar',
          email: 'tanvi.b@yahoo.com',
          phone: '+91 95432 45673',
          fatherName: 'Rajiv Bhatnagar',
          motherName: 'Monika Bhatnagar',
          gender: 'Female',
          dateOfBirth: '2005-06-30',
          category: 'EWS',
          state: 'Uttar Pradesh',
          address: 'Sector 62, Noida, Uttar Pradesh 201309',
          department: 'Computer Science & Engineering',
          degree: 'B.Tech',
          academicTerm: '2026-2027 Session',
          classXPercentage: 95.8,
          classXIIPercentage: 94.0,
          entranceExamScore: 'JEE Main: 99.1 Percentile',
          status: 'Under Review',
          verificationChecklist: {
            classXMarksheet: true,
            classXIIMarksheet: true,
            identityProof: true,
            migrationCertificate: false
          },
          appliedDate: new Date(Date.now() - 1000 * 60 * 720).toISOString()
        },
        {
          id: 'adm-005',
          applicationNumber: 'APP-2026-8805',
          applicantName: 'Karthik Raja',
          email: 'karthik.r@gmail.com',
          phone: '+91 94321 56784',
          fatherName: 'Ramaswamy Raja',
          motherName: 'Lakshmi Raja',
          gender: 'Male',
          dateOfBirth: '2004-11-08',
          category: 'SC',
          state: 'Tamil Nadu',
          address: 'Anna Nagar West, Chennai, Tamil Nadu 600040',
          department: 'Biotechnology & Life Sciences',
          degree: 'B.Tech',
          academicTerm: '2026-2027 Session',
          classXPercentage: 88.5,
          classXIIPercentage: 87.0,
          entranceExamScore: 'CUET: 680/800',
          status: 'Approved',
          generatedStudentId: '2026BT1018',
          enrolledStudentId: 'std-302',
          verificationChecklist: {
            classXMarksheet: true,
            classXIIMarksheet: true,
            identityProof: true,
            casteCertificate: true,
            migrationCertificate: true,
            verifiedBy: 'Central Admissions Cell',
            verifiedAt: new Date(Date.now() - 1000 * 60 * 1200).toISOString()
          },
          appliedDate: new Date(Date.now() - 1000 * 60 * 1440).toISOString()
        }
      ];
      admissions.forEach(a => dbStore.admissions.set(a.id, a));
    }

    // Seed Students if empty
    if (dbStore.students.size === 0) {
      const students: StudentRecord[] = [
        {
          id: 'std-1',
          studentId: '2024CSE1001',
          fullName: 'Aarav Sharma',
          email: 'aarav.sharma@scholarcore.edu.in',
          phone: '+91 98765 43210',
          department: 'Computer Science & Engineering',
          gender: 'Male',
          status: 'Active',
          enrollmentYear: 2024,
          currentSemester: 3,
          currentYear: 2,
          academicBatch: '2024-2028',
          attendancePercentage: 88.5,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 8.95, // 10.0 CGPA scale
          createdAt: '2024-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2004-03-14',
          address: 'B-104, Vasant Kunj, New Delhi, Delhi 110070',
          guardianName: 'Rajesh Sharma',
          guardianPhone: '+91 98112 34567'
        },
        {
          id: 'std-2',
          studentId: '2023ECE1014',
          fullName: 'Ananya Iyer',
          email: 'ananya.iyer@scholarcore.edu.in',
          phone: '+91 97123 45678',
          department: 'Electronics & Communication',
          gender: 'Female',
          status: 'Active',
          enrollmentYear: 2023,
          currentSemester: 5,
          currentYear: 3,
          academicBatch: '2023-2027',
          attendancePercentage: 92.0,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 9.40,
          createdAt: '2023-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2005-07-22',
          address: '45 Anna Salai, T. Nagar, Chennai, Tamil Nadu 600017',
          guardianName: 'Subramanian Iyer',
          guardianPhone: '+91 94440 12345'
        },
        {
          id: 'std-3',
          studentId: '2024ME1022',
          fullName: 'Rohan Verma',
          email: 'rohan.verma@scholarcore.edu.in',
          phone: '+91 96543 21098',
          department: 'Mechanical Engineering',
          gender: 'Male',
          status: 'Active',
          enrollmentYear: 2024,
          currentSemester: 3,
          currentYear: 2,
          academicBatch: '2024-2028',
          attendancePercentage: 68.0,
          backlogsCount: 3,
          feeStatus: 'Due',
          disciplinaryClearance: true,
          gpa: 8.10,
          createdAt: '2024-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2004-11-05',
          address: '12 Gomti Nagar, Lucknow, Uttar Pradesh 226010',
          guardianName: 'Manoj Verma',
          guardianPhone: '+91 98390 54321'
        },
        {
          id: 'std-4',
          studentId: '2022BT1005',
          fullName: 'Diya Deshmukh',
          email: 'diya.deshmukh@scholarcore.edu.in',
          phone: '+91 95432 10987',
          department: 'Biotechnology & Life Sciences',
          gender: 'Female',
          status: 'Active',
          enrollmentYear: 2022,
          currentSemester: 7,
          currentYear: 4,
          academicBatch: '2022-2026',
          attendancePercentage: 96.5,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 9.80,
          createdAt: '2022-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2003-01-18',
          address: '78 FC Road, Shivaji Nagar, Pune, Maharashtra 411005',
          guardianName: 'Vijay Deshmukh',
          guardianPhone: '+91 98220 98765'
        },
        {
          id: 'std-5',
          studentId: '2023EEE1008',
          fullName: 'Ishaan Gupta',
          email: 'ishaan.gupta@scholarcore.edu.in',
          phone: '+91 94321 09876',
          department: 'Electrical & Electronics',
          gender: 'Male',
          status: 'Active',
          enrollmentYear: 2023,
          currentSemester: 5,
          currentYear: 3,
          academicBatch: '2023-2027',
          attendancePercentage: 81.0,
          backlogsCount: 1,
          feeStatus: 'Partial',
          disciplinaryClearance: true,
          gpa: 8.65,
          createdAt: '2023-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2005-09-30',
          address: 'C-88 Malviya Nagar, Jaipur, Rajasthan 302017',
          guardianName: 'Suresh Gupta',
          guardianPhone: '+91 94140 87654'
        },
        {
          id: 'std-6',
          studentId: '2021MBA1002',
          fullName: 'Priya Patel',
          email: 'priya.patel@scholarcore.edu.in',
          phone: '+91 93210 98765',
          department: 'Department of Management Studies',
          gender: 'Female',
          status: 'Graduated',
          enrollmentYear: 2021,
          currentSemester: 8,
          currentYear: 4,
          academicBatch: '2021-2025',
          attendancePercentage: 94.0,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 9.25,
          createdAt: '2021-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2002-05-12',
          address: '102 CG Road, Navrangpura, Ahmedabad, Gujarat 380009',
          guardianName: 'Ramesh Patel',
          guardianPhone: '+91 98980 12345'
        },
        {
          id: 'std-7',
          studentId: '2024CSE1089',
          fullName: 'Rahul Nair',
          email: 'rahul.nair@scholarcore.edu.in',
          phone: '+91 92109 87654',
          department: 'Computer Science & Engineering',
          gender: 'Male',
          status: 'Active',
          enrollmentYear: 2024,
          currentSemester: 3,
          currentYear: 2,
          academicBatch: '2024-2028',
          attendancePercentage: 89.2,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 8.45,
          createdAt: '2024-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2004-08-25',
          address: '15 Marine Drive, Ernakulam, Kochi, Kerala 682031',
          guardianName: 'Unnikrishnan Nair',
          guardianPhone: '+91 94470 65432'
        },
        {
          id: 'std-8',
          studentId: '2023CE1011',
          fullName: 'Kavya Joshi',
          email: 'kavya.joshi@scholarcore.edu.in',
          phone: '+91 91098 76543',
          department: 'Mechanical Engineering',
          gender: 'Female',
          status: 'Inactive',
          enrollmentYear: 2023,
          currentSemester: 4,
          currentYear: 2,
          academicBatch: '2023-2027',
          attendancePercentage: 72.0,
          backlogsCount: 2,
          feeStatus: 'Due',
          disciplinaryClearance: false,
          gpa: 7.90,
          createdAt: '2023-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2005-12-04',
          address: '5 Rajpur Road, Dehradun, Uttarakhand 248001',
          guardianName: 'Prakash Joshi',
          guardianPhone: '+91 98370 12345'
        },
        {
          id: 'std-9',
          studentId: '2022CSE1003',
          fullName: 'Vikramaditya Singh',
          email: 'vikram.singh@scholarcore.edu.in',
          phone: '+91 90987 65432',
          department: 'Computer Science & Engineering',
          gender: 'Male',
          status: 'Active',
          enrollmentYear: 2022,
          currentSemester: 7,
          currentYear: 4,
          academicBatch: '2022-2026',
          attendancePercentage: 98.0,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 9.60,
          createdAt: '2022-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2004-04-01',
          address: '42 Arera Colony, Bhopal, Madhya Pradesh 462016',
          guardianName: 'Digvijay Singh',
          guardianPhone: '+91 94250 87654'
        },
        {
          id: 'std-10',
          studentId: '2024DS1007',
          fullName: 'Snigdha Roy',
          email: 'snigdha.roy@scholarcore.edu.in',
          phone: '+91 89876 54321',
          department: 'Biotechnology & Life Sciences',
          gender: 'Female',
          status: 'Active',
          enrollmentYear: 2024,
          currentSemester: 3,
          currentYear: 2,
          academicBatch: '2024-2028',
          attendancePercentage: 91.5,
          backlogsCount: 0,
          feeStatus: 'Paid',
          disciplinaryClearance: true,
          gpa: 9.15,
          createdAt: '2024-07-15T09:00:00Z',
          photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=250',
          dateOfBirth: '2003-10-28',
          address: '88 Salt Lake Sector V, Kolkata, West Bengal 700091',
          guardianName: 'Debashis Roy',
          guardianPhone: '+91 98300 54321'
        }
      ];
      students.forEach(s => dbStore.students.set(s.id, s));
    }

    // Seed Guardians if empty
    if (dbStore.guardians.size === 0) {
      const initialGuardians: GuardianRecord[] = [
        {
          id: 'grd-101',
          guardianId: 'GRD-2026-001',
          fatherName: 'Rajesh Sharma',
          fatherOccupation: 'Senior Software Architect',
          fatherPhone: '+91 98112 34567',
          fatherEmail: 'rajesh.sharma@gmail.com',
          motherName: 'Sunita Sharma',
          motherOccupation: 'High School Vice Principal',
          motherPhone: '+91 98112 34568',
          motherEmail: 'sunita.sharma@gmail.com',
          guardianName: 'Rajesh Sharma',
          relationship: 'Father',
          occupation: 'Senior Software Architect',
          primaryPhone: '+91 98112 34567',
          email: 'rajesh.sharma@gmail.com',
          annualIncome: 2800000,
          emergencyContactName: 'Alok Sharma',
          emergencyContactPhone: '+91 98112 99887',
          emergencyContactAltPhone: '+91 98112 99888',
          emergencyRelationship: 'Uncle (Father Brother)',
          emergencyAddress: 'C-12 Vasant Kunj, New Delhi 110070',
          residentialAddress: 'B-104, Vasant Kunj, New Delhi, Delhi',
          city: 'New Delhi',
          state: 'Delhi',
          zipCode: '110070',
          country: 'India',
          mappedStudentIds: ['std-1'],
          status: 'Active',
          createdAt: new Date('2024-07-15').toISOString()
        },
        {
          id: 'grd-102',
          guardianId: 'GRD-2026-002',
          fatherName: 'Subramanian Iyer',
          fatherOccupation: 'Chartered Accountant',
          fatherPhone: '+91 94440 12345',
          fatherEmail: 'subramanian.iyer@ca.in',
          motherName: 'Meenakshi Iyer',
          motherOccupation: 'Classical Music Instructor',
          motherPhone: '+91 94440 54321',
          motherEmail: 'meenakshi.iyer@gmail.com',
          guardianName: 'Subramanian Iyer',
          relationship: 'Father',
          occupation: 'Chartered Accountant',
          primaryPhone: '+91 94440 12345',
          email: 'subramanian.iyer@ca.in',
          annualIncome: 3200000,
          emergencyContactName: 'Venkatesh Iyer',
          emergencyContactPhone: '+91 94440 88776',
          emergencyRelationship: 'Local Guardian (Uncle)',
          emergencyAddress: '12 Cathedral Road, Chennai 600086',
          residentialAddress: '45 Anna Salai, T. Nagar, Chennai, Tamil Nadu',
          city: 'Chennai',
          state: 'Tamil Nadu',
          zipCode: '600017',
          country: 'India',
          mappedStudentIds: ['std-2'],
          status: 'Active',
          createdAt: new Date('2023-07-15').toISOString()
        },
        {
          id: 'grd-103',
          guardianId: 'GRD-2026-003',
          fatherName: 'Manoj Verma',
          fatherOccupation: 'Civil Engineer (PWD)',
          fatherPhone: '+91 98390 54321',
          fatherEmail: 'm.verma.pwd@gov.in',
          motherName: 'Aarti Verma',
          motherOccupation: 'Homemaker',
          motherPhone: '+91 98390 54322',
          motherEmail: 'aarti.verma@gmail.com',
          guardianName: 'Manoj Verma',
          relationship: 'Father',
          occupation: 'Civil Engineer (PWD)',
          primaryPhone: '+91 98390 54321',
          email: 'm.verma.pwd@gov.in',
          annualIncome: 1800000,
          emergencyContactName: 'Sanjay Verma',
          emergencyContactPhone: '+91 98390 11223',
          emergencyRelationship: 'Brother',
          emergencyAddress: 'Hazratganj Main Road, Lucknow 226001',
          residentialAddress: '12 Gomti Nagar, Lucknow, Uttar Pradesh',
          city: 'Lucknow',
          state: 'Uttar Pradesh',
          zipCode: '226010',
          country: 'India',
          mappedStudentIds: ['std-3'],
          status: 'Active',
          createdAt: new Date('2024-07-15').toISOString()
        },
        {
          id: 'grd-104',
          guardianId: 'GRD-2026-004',
          fatherName: 'Vijay Deshmukh',
          fatherOccupation: 'Manufacturing Business Owner',
          fatherPhone: '+91 98220 98765',
          fatherEmail: 'vijay@deshmukhengg.com',
          motherName: 'Radhika Deshmukh',
          motherOccupation: 'Botanist & Research Scientist',
          motherPhone: '+91 98220 98766',
          motherEmail: 'radhika.deshmukh@unipune.ac.in',
          guardianName: 'Vijay Deshmukh',
          relationship: 'Father',
          occupation: 'Manufacturing Business Owner',
          primaryPhone: '+91 98220 98765',
          email: 'vijay@deshmukhengg.com',
          annualIncome: 4500000,
          emergencyContactName: 'Anand Deshmukh',
          emergencyContactPhone: '+91 98220 33445',
          emergencyRelationship: 'Paternal Uncle',
          emergencyAddress: '24 Karve Road, Kothrud, Pune 411038',
          residentialAddress: '78 FC Road, Shivaji Nagar, Pune, Maharashtra',
          city: 'Pune',
          state: 'Maharashtra',
          zipCode: '411005',
          country: 'India',
          mappedStudentIds: ['std-4'],
          status: 'Active',
          createdAt: new Date('2022-07-15').toISOString()
        },
        {
          id: 'grd-105',
          guardianId: 'GRD-2026-005',
          fatherName: 'Debashis Roy',
          fatherOccupation: 'Biotech General Manager',
          fatherPhone: '+91 98300 54321',
          fatherEmail: 'debashis.roy@biocon.com',
          motherName: 'Barnali Roy',
          motherOccupation: 'Senior Research Scientist',
          motherPhone: '+91 98300 54322',
          motherEmail: 'barnali.roy@gmail.com',
          guardianName: 'Debashis Roy',
          relationship: 'Father',
          occupation: 'Biotech General Manager',
          primaryPhone: '+91 98300 54321',
          email: 'debashis.roy@biocon.com',
          annualIncome: 3600000,
          emergencyContactName: 'Subhasis Roy',
          emergencyContactPhone: '+91 98300 77665',
          emergencyRelationship: 'Uncle',
          emergencyAddress: 'Salt Lake Block EC, Kolkata 700064',
          residentialAddress: '88 Salt Lake Sector V, Kolkata, West Bengal',
          city: 'Kolkata',
          state: 'West Bengal',
          zipCode: '700091',
          country: 'India',
          mappedStudentIds: ['std-10'],
          status: 'Active',
          createdAt: new Date('2024-07-15').toISOString()
        }
      ];
      initialGuardians.forEach(g => dbStore.guardians.set(g.id, g));
    }

    // Seed Activities if empty
    if (dbStore.activities.length === 0) {
      dbStore.activities = [
        {
          id: 'act-101',
          title: 'New Admission Application Received',
          description: 'Siddharth Mukherjee applied for 2026-27 B.Tech CSE Intake.',
          category: 'Admission',
          actorName: 'Siddharth Mukherjee',
          actorRole: 'Applicant',
          timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
          badgeType: 'gold'
        },
        {
          id: 'act-102',
          title: 'Admission Status Approved',
          description: 'Rohan Deshpande approved by Academic Registrar Cell.',
          category: 'Admission',
          actorName: 'Sunita Deshmukh',
          actorRole: 'Academic Registrar',
          timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
          badgeType: 'success'
        },
        {
          id: 'act-103',
          title: 'Academic Bank of Credits (ABC ID) Synced',
          description: 'Synced 1,240 student ABC credit IDs with Digilocker portal.',
          category: 'Academic',
          actorName: 'Prof. Ramesh Kulkarni',
          actorRole: 'Faculty / HOD',
          timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
          badgeType: 'info'
        },
        {
          id: 'act-104',
          title: 'Semester Fee Collection Verified (UPI/NEFT)',
          description: '₹1,25,000 Semester IV Tuition Fee verified for Aarav Sharma.',
          category: 'Fee',
          actorName: 'Accounts Bureau',
          actorRole: 'System',
          timestamp: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
          badgeType: 'success'
        },
        {
          id: 'act-105',
          title: 'NEP 2020 Curriculum Compliance Verified',
          description: 'Multidisciplinary credit choices and skill-based electives mapped.',
          category: 'System',
          actorName: 'Dr. Rajeshwar Sharma',
          actorRole: 'Super Admin',
          timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
          badgeType: 'warning'
        }
      ];
    }

    // Seed Notifications if empty
    if (dbStore.notifications.length === 0) {
      dbStore.notifications = [
        {
          id: 'notif-1',
          title: '2026-27 Merit Admissions Closing Soon',
          message: '48 candidate applications pending verification at Central Admissions Cell.',
          priority: 'high',
          category: 'Admission',
          timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
          read: false,
          actionUrl: '/dashboard'
        },
        {
          id: 'notif-2',
          title: 'Mid-Term CGPA Internal Marks Submission',
          message: 'Faculty members are requested to upload internal assessment marks on SIMS portal.',
          priority: 'medium',
          category: 'Academic',
          timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
          read: false
        },
        {
          id: 'notif-3',
          title: 'Digilocker & ABC Credit Portal Sync',
          message: 'Automatic credit sync scheduled on Sunday 02:00 IST.',
          priority: 'low',
          category: 'System',
          timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
          read: true
        }
      ];
    }

    // Seed Documents if empty
    if (dbStore.documents.size === 0) {
      const initialDocs: DocumentRecord[] = [
        {
          id: 'doc-1',
          documentId: 'DOC-2026-001',
          studentId: 'std-1',
          studentRollNo: '2023CSE014',
          studentName: 'Aarav Sharma',
          documentType: 'Aadhaar',
          title: 'Aadhaar Card - UIDAI Verified',
          fileName: 'Aadhaar_Aarav_Sharma.pdf',
          fileType: 'application/pdf',
          fileSize: '1.4 MB',
          fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
          verificationStatus: 'Verified',
          verifiedBy: 'Dr. Rajeshwar Sharma',
          verificationDate: new Date(Date.now() - 1000 * 3600 * 24 * 10).toISOString(),
          remarks: 'Verified via UIDAI Digilocker QR scan.',
          uploadDate: new Date(Date.now() - 1000 * 3600 * 24 * 12).toISOString()
        },
        {
          id: 'doc-2',
          documentId: 'DOC-2026-002',
          studentId: 'std-1',
          studentRollNo: '2023CSE014',
          studentName: 'Aarav Sharma',
          documentType: 'Birth Certificate',
          title: 'Municipal Birth Certificate',
          fileName: 'BirthCert_Aarav.pdf',
          fileType: 'application/pdf',
          fileSize: '890 KB',
          fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
          verificationStatus: 'Verified',
          verifiedBy: 'Admissions Officer',
          verificationDate: new Date(Date.now() - 1000 * 3600 * 24 * 8).toISOString(),
          remarks: 'Date of birth matches 15-Aug-2003.',
          uploadDate: new Date(Date.now() - 1000 * 3600 * 24 * 10).toISOString()
        },
        {
          id: 'doc-3',
          documentId: 'DOC-2026-003',
          studentId: 'std-1',
          studentRollNo: '2023CSE014',
          studentName: 'Aarav Sharma',
          documentType: 'Passport Photo',
          title: 'Official Passport Photograph (35x45mm)',
          fileName: 'PassportPhoto_Aarav.jpg',
          fileType: 'image/jpeg',
          fileSize: '450 KB',
          fileUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
          verificationStatus: 'Verified',
          verifiedBy: 'Academic Registrar',
          verificationDate: new Date(Date.now() - 1000 * 3600 * 24 * 5).toISOString(),
          remarks: 'Standard white background photo confirmed.',
          uploadDate: new Date(Date.now() - 1000 * 3600 * 24 * 7).toISOString()
        },
        {
          id: 'doc-4',
          documentId: 'DOC-2026-004',
          studentId: 'std-1',
          studentRollNo: '2023CSE014',
          studentName: 'Aarav Sharma',
          documentType: 'Marks Cards',
          title: '10th SSLC Class Marks Sheet (CBSE)',
          fileName: '10th_Marksheet_Aarav.pdf',
          fileType: 'application/pdf',
          fileSize: '2.1 MB',
          fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
          verificationStatus: 'Verified',
          verifiedBy: 'Admissions Desk',
          verificationDate: new Date(Date.now() - 1000 * 3600 * 24 * 3).toISOString(),
          remarks: '94.8% aggregate verified.',
          uploadDate: new Date(Date.now() - 1000 * 3600 * 24 * 6).toISOString()
        },
        {
          id: 'doc-5',
          documentId: 'DOC-2026-005',
          studentId: 'std-2',
          studentRollNo: '2023ECE028',
          studentName: 'Ananya Iyer',
          documentType: 'Transfer Certificate',
          title: 'Higher Secondary Transfer Certificate',
          fileName: 'TC_Ananya_Iyer.pdf',
          fileType: 'application/pdf',
          fileSize: '1.2 MB',
          fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
          verificationStatus: 'Pending Verification',
          remarks: 'Awaiting original hardcopy submission for seal verification.',
          uploadDate: new Date(Date.now() - 1000 * 3600 * 24 * 2).toISOString()
        },
        {
          id: 'doc-6',
          documentId: 'DOC-2026-006',
          studentId: 'std-3',
          studentRollNo: '2022ME009',
          studentName: 'Rohan Verma',
          documentType: 'Marks Cards',
          title: '12th Class Pre-University Statement of Marks',
          fileName: '12th_Marksheet_Rohan.pdf',
          fileType: 'application/pdf',
          fileSize: '1.8 MB',
          fileUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=800&q=80',
          verificationStatus: 'Re-upload Requested',
          remarks: 'Scanned image is blurry around Math marks column. Please re-upload clear PDF scan.',
          uploadDate: new Date(Date.now() - 1000 * 3600 * 12).toISOString()
        }
      ];

      initialDocs.forEach(d => dbStore.documents.set(d.id, d));
    }

    // Seed Promotion History if empty
    if (dbStore.promotionHistory.size === 0) {
      const initialPromotions = [
        {
          id: 'prm-101',
          studentDbId: 'std-1',
          studentId: '2024CSE1001',
          studentName: 'Aarav Sharma',
          department: 'Computer Science & Engineering',
          promotionType: 'Semester Promotion' as const,
          previousSemester: 2,
          newSemester: 3,
          previousYear: 1,
          newYear: 2,
          promotedBy: 'Dean of Academic Affairs',
          promotedAt: new Date(Date.now() - 1000 * 3600 * 24 * 15).toISOString(),
          academicSession: '2025-2026 Even Sem',
          status: 'Promoted' as const,
          remarks: 'Regular promotion upon passing Semester 2 examinations with GPA 8.95.',
          validationPassed: true,
          validationCheckSummary: {
            attendanceOk: true,
            attendanceVal: 88.5,
            backlogsOk: true,
            backlogsVal: 0,
            feeOk: true,
            feeVal: 'Paid',
            disciplineOk: true
          }
        },
        {
          id: 'prm-102',
          studentDbId: 'std-2',
          studentId: '2023ECE1014',
          studentName: 'Ananya Iyer',
          department: 'Electronics & Communication',
          promotionType: 'Year Promotion' as const,
          previousSemester: 4,
          newSemester: 5,
          previousYear: 2,
          newYear: 3,
          promotedBy: 'Academic Registrar',
          promotedAt: new Date(Date.now() - 1000 * 3600 * 24 * 20).toISOString(),
          academicSession: '2025-2026 Academic Year',
          status: 'Promoted' as const,
          remarks: 'Promoted to 3rd Year Electronics with High Distinction (9.40 GPA).',
          validationPassed: true,
          validationCheckSummary: {
            attendanceOk: true,
            attendanceVal: 92.0,
            backlogsOk: true,
            backlogsVal: 0,
            feeOk: true,
            feeVal: 'Paid',
            disciplineOk: true
          }
        },
        {
          id: 'prm-103',
          studentDbId: 'std-5',
          studentId: '2023EEE1008',
          studentName: 'Ishaan Gupta',
          department: 'Electrical & Electronics',
          promotionType: 'Conditional Promotion' as const,
          previousSemester: 4,
          newSemester: 5,
          previousYear: 2,
          newYear: 3,
          promotedBy: 'HOD Electrical Engg',
          promotedAt: new Date(Date.now() - 1000 * 3600 * 24 * 5).toISOString(),
          academicSession: '2025-2026 Even Sem',
          status: 'Conditional' as const,
          remarks: 'Conditional promotion granted with 1 backlog in Electric Circuits. Must clear in upcoming supplementary session.',
          validationPassed: false,
          validationCheckSummary: {
            attendanceOk: true,
            attendanceVal: 81.0,
            backlogsOk: false,
            backlogsVal: 1,
            feeOk: true,
            feeVal: 'Partial',
            disciplineOk: true
          }
        }
      ];

      initialPromotions.forEach(p => dbStore.promotionHistory.set(p.id, p));
    }

    // Seed Alumni Records if empty
    if (dbStore.alumni.size === 0) {
      const initialAlumni: AlumniRecord[] = [
        {
          id: 'alm-101',
          studentId: '2018CSE0042',
          fullName: 'Aarav Sharma',
          email: 'aarav.sharma@alumni.scholarcore.edu',
          phone: '+91 98112 34567',
          graduationYear: 2022,
          department: 'Computer Science & Engineering',
          degree: 'B.Tech CSE',
          cgpa: 9.42,
          photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
          gender: 'Male',
          employmentStatus: 'Employed',
          currentCompany: 'Google India',
          designation: 'Staff Software Engineer',
          industry: 'Information Technology',
          salaryBand: '32 - 40 LPA',
          workLocation: 'Bengaluru, India',
          linkedinUrl: 'https://linkedin.com/in/aarav-sharma-cs',
          githubUrl: 'https://github.com/aaravsharma',
          personalWebsite: 'https://aaravsharma.dev',
          currentCity: 'Bengaluru',
          currentCountry: 'India',
          permanentAddress: '102 Indiranagar 10th Main, Bengaluru, KA',
          networkingOptIn: true,
          achievements: ['Google Outstanding Engineer Award 2024', 'Published 2 IEEE AI research papers'],
          givingHistory: [
            {
              id: 'g-1',
              amount: 50000,
              currency: 'INR',
              purpose: 'CSE Department Research Lab Fund',
              date: '2024-11-15',
              receiptNumber: 'REC-2024-0891'
            }
          ],
          createdAt: new Date('2022-06-20').toISOString(),
          updatedAt: new Date('2025-01-10').toISOString(),
        },
        {
          id: 'alm-102',
          studentId: '2019ECE0019',
          fullName: 'Priyanka Nambiar',
          email: 'priyanka.n@alumni.scholarcore.edu',
          phone: '+91 97441 88203',
          graduationYear: 2023,
          department: 'Electronics & Communication',
          degree: 'B.Tech ECE',
          cgpa: 9.15,
          photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
          gender: 'Female',
          employmentStatus: 'Employed',
          currentCompany: 'Qualcomm',
          designation: 'Senior Hardware Systems Engineer',
          industry: 'Semiconductors',
          salaryBand: '22 - 28 LPA',
          workLocation: 'Hyderabad, India',
          linkedinUrl: 'https://linkedin.com/in/priyanka-nambiar',
          currentCity: 'Hyderabad',
          currentCountry: 'India',
          networkingOptIn: true,
          achievements: ['Patent holder: Ultra-low power IoT Transceiver'],
          givingHistory: [
            {
              id: 'g-2',
              amount: 25000,
              currency: 'INR',
              purpose: 'Merit Scholarship Endowment',
              date: '2025-02-01',
              receiptNumber: 'REC-2025-0112'
            }
          ],
          createdAt: new Date('2023-06-18').toISOString(),
          updatedAt: new Date('2025-02-01').toISOString(),
        },
        {
          id: 'alm-103',
          studentId: '2017ME0088',
          fullName: 'Vikram Malhotra',
          email: 'vikram.m@alumni.scholarcore.edu',
          phone: '+1 650 492 1109',
          graduationYear: 2021,
          department: 'Mechanical Engineering',
          degree: 'B.Tech ME',
          cgpa: 8.85,
          photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
          gender: 'Male',
          employmentStatus: 'Self-Employed / Founder',
          currentCompany: 'AeroDynamics Robotics Inc.',
          designation: 'Founder & CTO',
          industry: 'Aerospace & Robotics',
          salaryBand: '$120,000 - $160,000 / yr',
          workLocation: 'San Francisco, USA',
          linkedinUrl: 'https://linkedin.com/in/vikram-malhotra-aero',
          githubUrl: 'https://github.com/vmalhotra',
          personalWebsite: 'https://aerodynamicsrobotics.io',
          currentCity: 'San Francisco',
          currentCountry: 'USA',
          networkingOptIn: true,
          achievements: ['Forbes 30 Under 30 Enterprise Tech', 'Raised $4.5M Seed Round'],
          givingHistory: [
            {
              id: 'g-3',
              amount: 250000,
              currency: 'INR',
              purpose: 'Robotics & Automation Incubator Grant',
              date: '2024-09-10',
              receiptNumber: 'REC-2024-0412'
            }
          ],
          createdAt: new Date('2021-06-25').toISOString(),
          updatedAt: new Date('2025-01-20').toISOString(),
        },
        {
          id: 'alm-104',
          studentId: '2020BT0005',
          fullName: 'Sneha Chawla',
          email: 'sneha.c@alumni.scholarcore.edu',
          phone: '+44 20 7946 0912',
          graduationYear: 2024,
          department: 'Biotechnology & Life Sciences',
          degree: 'M.Tech Biotechnology',
          cgpa: 9.60,
          photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
          gender: 'Female',
          employmentStatus: 'Higher Studies',
          currentCompany: 'University of Cambridge',
          designation: 'Ph.D. Research Scholar in Genomic Engineering',
          industry: 'Research & Academia',
          salaryBand: 'Stipend / Research Fellowship',
          workLocation: 'Cambridge, UK',
          higherEducation: {
            institution: 'University of Cambridge',
            degree: 'Ph.D.',
            fieldOfStudy: 'Genomic Engineering & CRISPR Systems',
            completionYear: 2028,
            country: 'United Kingdom'
          },
          linkedinUrl: 'https://linkedin.com/in/sneha-chawla-biotech',
          currentCity: 'Cambridge',
          currentCountry: 'UK',
          networkingOptIn: true,
          achievements: ['Commonwealth PhD Fellowship Recipient 2024'],
          createdAt: new Date('2024-06-30').toISOString(),
          updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
          id: 'alm-105',
          studentId: '2019MBA0002',
          fullName: 'Rohan Mehra',
          email: 'rohan.mehra@alumni.scholarcore.edu',
          phone: '+91 98200 44112',
          graduationYear: 2021,
          department: 'Department of Management Studies',
          degree: 'MBA Finance',
          cgpa: 8.90,
          photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
          gender: 'Male',
          employmentStatus: 'Employed',
          currentCompany: 'McKinsey & Company',
          designation: 'Engagement Manager',
          industry: 'Management Consulting',
          salaryBand: '35 - 45 LPA',
          workLocation: 'Mumbai, India',
          linkedinUrl: 'https://linkedin.com/in/rohanmehra-consulting',
          currentCity: 'Mumbai',
          currentCountry: 'India',
          networkingOptIn: true,
          givingHistory: [
            {
              id: 'g-4',
              amount: 100000,
              currency: 'INR',
              purpose: 'Annual Student Sports Championship Sponsorship',
              date: '2024-12-05',
              receiptNumber: 'REC-2024-0990'
            }
          ],
          createdAt: new Date('2021-06-15').toISOString(),
          updatedAt: new Date('2025-01-05').toISOString(),
        },
        {
          id: 'alm-106',
          studentId: '2018EEE0033',
          fullName: 'Kavita Reddy',
          email: 'kavita.r@alumni.scholarcore.edu',
          phone: '+91 99801 22334',
          graduationYear: 2022,
          department: 'Electrical & Electronics',
          degree: 'B.Tech EEE',
          cgpa: 8.40,
          photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
          gender: 'Female',
          employmentStatus: 'Employed',
          currentCompany: 'Tesla Energy',
          designation: 'Power Grid Specialist Engineer',
          industry: 'Renewable Energy',
          salaryBand: '20 - 25 LPA',
          workLocation: 'Bengaluru, India',
          linkedinUrl: 'https://linkedin.com/in/kavita-reddy-eee',
          currentCity: 'Bengaluru',
          currentCountry: 'India',
          networkingOptIn: false,
          createdAt: new Date('2022-06-18').toISOString(),
          updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
          id: 'alm-107',
          studentId: '2020CSE0099',
          fullName: 'Karan Verma',
          email: 'karan.verma@alumni.scholarcore.edu',
          phone: '+91 91102 77412',
          graduationYear: 2024,
          department: 'Computer Science & Engineering',
          degree: 'B.Tech CSE',
          cgpa: 7.80,
          photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=250&q=80',
          gender: 'Male',
          employmentStatus: 'Seeking Opportunities',
          industry: 'Information Technology',
          workLocation: 'New Delhi, India',
          linkedinUrl: 'https://linkedin.com/in/karanverma-dev',
          currentCity: 'New Delhi',
          currentCountry: 'India',
          networkingOptIn: true,
          notes: 'Actively applying for Full Stack Web Developer & DevOps positions.',
          createdAt: new Date('2024-06-28').toISOString(),
          updatedAt: new Date('2025-01-25').toISOString(),
        }
      ];

      initialAlumni.forEach(a => dbStore.alumni.set(a.id, a));
    }
  }
}
